import { GetServerSideProps } from 'next'
import { useRouter } from "next/router";
import moment from 'moment';
import axios from "axios";
import Head from "next/head";
import styles from "styles/Home.module.css";
import detailStyles from "styles/Detail.module.css";
import DailyWeatherCard from "components/dailyWeatherCard";
import InfoCard from 'components/infoCard';

interface Props {
  weather: any;
}

const CityDetail = ({weather}: Props) => {
  const router = useRouter();
  const { title } = router.query;

  return (
    <div>
      <Head>
        <title>{title} - WeahterPP</title>
        <meta name="description" content="Generated by SRD" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {weather?.daily && (
        <div className={styles.dailyWeatherWidget}>
          <h2>{title}</h2>
          <div className={styles.dailyWeatherCardContainer}>
            {weather?.daily.map((daily: any, index: number) => (
              <DailyWeatherCard daily={daily} key={index} />
            ))}
          </div>
        </div>
      )}
      <span className={detailStyles.infoTitle}>Todays Highlighs</span>
      <div className={detailStyles.infoContainer}>
        <InfoCard title={'Tempeture'} value={weather.current.temp} />
        <InfoCard title={'Feels Like'} value={weather.current.feels_like} />
        <InfoCard title={'Humidity'} value={weather.current.humidity} />
        <InfoCard title={'Pressure'} value={weather.current.pressure} />
      </div>
      <div className={detailStyles.infoContainer}>
        <InfoCard title={'Sunrise'} value={moment(weather.current.sunrise).format('HH:mm')} />
        <InfoCard title={'Sunrise'} value={moment(weather.current.sunrise).format('HH:mm')} />
        <InfoCard title={'UV Index'} value={weather.current.uvi} />
        <InfoCard title={'Wind Speed'} value={weather.current.wind_speed} />
      </div>
    </div>
  )
}

export default CityDetail;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const query = context.query;

  if (query) {
    const { lat, lon } = query;
    const { data } = await axios.get(
      `${process.env.api_url}/onecall?lat=${lat}&lon=${lon}&appid=${process.env.api_key}&units=metric`
    );
    return {
      props: {
        weather: data
      }
    }
  }
  return {
    props: {}
  }
}
